### ISSUE TITLE
[1.12.1] Various bugs (and a complaint!)

### ISSUE THREAD

**Issue by Tokeli** [MiningMark48/Dimensional-Ores#10]
Psssst. Your Aluminum is ore-dicted with the British spelling "aluminium", yet every single other mod uses the US spelling, so it doesn't work with anything that requires aluminum at all.

Uranium also spawns *far* more often than in any other mod, and it seems like all of your nether/end ores can be mined with a stone pick, as I was able to collect everything (including cobalt) with one.

**Comment by MiningMark48** [comment]
The ore dict bug was something I thought I fix and apparently did not.

I also do realize uranium is far too common, I'll have to tweak the spawn rate though I do hope to have configurable options soon. Until an update, if you wish to remove the uranium from spawning there is a configuration option for that.

**Comment by Tokeli** [comment]
Yeah, I love that your mod seems to be just about the only ore mod that adds Just The Basics to the other dimensions, and with some more config options it'd be the best!

The oredict and over-spawning are easy to fix with craft-tweaker and the config, the missing mining levels required removing everything expensive.

**Comment by MiningMark48** [comment]
Thanks 😉I'll have the issue(s) fixed soon. 

**EDIT:** Issue fixed, mod will be updated soon. Watch the [mod page](https://minecraft.curseforge.com/projects/dimensional-ores/files) for updates. Sorry for the trouble.
