### ISSUE TITLE
[0.0.3] NPE Crash

### ISSUE THREAD

**Issue by Alaberti** [MiningMark48/Dimensional-Ores#3]
I turned off overworld gen in your config, and it crashed my dedicated server.

Crash Report: http://pastebin.com/HqgLrgVi
Config: http://pastebin.com/Ci7TmERc

**Comment by Alaberti** [comment]
Crash Report: http://pastebin.com/HqgLrgVi
Config: http://pastebin.com/Ci7TmERc

**Comment by MiningMark48** [comment]
Thanks for the report, I'll look into the issue. Sorry for any inconvenience.
