### ISSUE TITLE
Some ore is not recognized for pulverizing/crushing

### ISSUE THREAD

**Issue by cragrim** [MiningMark48/Dimensional-Ores#5]
Vanilla ore is not recognized for crushing/ore doubling mechanics in any machines like the Thermal Expansion Pulverizer, IC2 Macerator or Crusher from ExtraUtilities.

This applies to Nether Iron Ore, Nether Gold Ore.
They also dont appear to be added to the ore dictionary.  
Modded ores like Tin and Copper work.

I tried adding them to the OreDictionary using CraftTweaker (MineTweaker)
val oreIron = <ore:oreIron>;
oreIron.add(<dimensionalores:nether_iron>);

It worked for crafting recipes but not for any machines. This is just a guess but maybe it need to be added earlier?

Best Regards :)

**Comment by MiningMark48** [comment]
I believe I know the issue at hand and it should be resolved in the next version.

**Comment by MiningMark48** [comment]
Fixed.

**Comment by cragrim** [comment]
I saw that you released Dimensional Ores v1.0.0 for MC 1.12 which I assume this is fixed in.
Will you also update 1.11.2?

**Comment by MiningMark48** [comment]
I probably will.
