### ISSUE TITLE
Aluminum Ore, Tinker's Construct.

### ISSUE THREAD

**Issue by PoyudiHytori** [MiningMark48/Dimensional-Ores#6]
The Aluminum Ore in this mod doesn't have an ingot or block, and even when using another mod, like Galactic Craft or Hardmode Ores, to add those in, Tinker's Construct does not recognize the Aluminum Ore from this mod as Aluminum. All the other ores I'm using with these mods have no issue with Tinker's Construct, and can turn into the ingots and blocks from Hardmode Ores. I'm using the 1.11.2 Version .04 of the Dimensional Ores mod.

**Comment by MiningMark48** [comment]
This was fixed in 1.12. I may fix for 1.11 sometime soon.
