### ISSUE TITLE
[1.12] Invalid registration attempt for an Ore Dictionary item 

### ISSUE THREAD

**Issue by FiveEYZ** [MiningMark48/Dimensional-Ores#7]
Don't know how urgent this is, but it says: "the mod responsible for the registration needs to correct this"

https://gist.github.com/FiveEYZ/f9894fe99e87ec5b9107adffaeed8236

using: 
- dimensionalores-1.12-1.0.0
- forge-1.12-14.21.1.2428-universal

**Comment by MiningMark48** [comment]
I'll look into this, thanks for the report. Thinking the Ore Dictionary is being registered to early.
