### ISSUE TITLE
java.lang.IllegalArgumentException: Stack can not be invalid!

### ISSUE THREAD

**Issue by rckymtnrfc** [MiningMark48/Dimensional-Ores#8]
I'm getting the following crash when using Dimensional Ores  1.12-1.0.0 (along with mininglib-1.12-1.0.1) when used with the Charcoal Pit mod.  I'm also using Forge 2426 but experienced the same crash with prior versions of Forge as well.

https://pastebin.com/ZA4wZpNy

I spoke to the author of Charcoal Pit and his response was "someone is registering a smelting recipe with a null input."  Hopefully that helps narrow down the issue.

Thank you

**Comment by MiningMark48** [comment]
I'll look into the issue, I believe I have an idea as to what is causing this issue.
