### ISSUE TITLE
bugs? and suggestions

### ISSUE THREAD

**Issue by shufunk** [MiningMark48/Dimensional-Ores#9]
I found your mod when working on my latest modpack for 1.12 but there are a few things that need to be addressed unless you are already aware of it I am sorry in advance to bringing this up. I made the following video explaining a few things.

https://youtu.be/1yUC4_R9jd8

**Comment by MiningMark48** [comment]
Just so I know, what version of Dimensional Ores are you using at the moment?

**Comment by MiningMark48** [comment]
**Addressing the bugs/features:**

- Ingots are compatible with mods via ore dictionary; if a mod doesn't use ore dictionary, then the ingots won't be used with that mod.
- I agree the cobalt ore should be diamond/obsidian level and this will be changed _soon_, though in the future this may be configurable (for all ores)


**Features coming but not addressed in video**
- Ores will be more configurable (this includes vein size, mining levels, and rarity as well as hardness and resistance)
- More ores will be added that are not currently supported


This issue will be closed once I change the cobalt ores's mining level.

**Comment by shufunk** [comment]
honestly when i installed the mods on my laptop i thought you still had just one version cause I have 1.0 on my PC but realized you just released 1.01 a few hours before i made that video i posted and i didn't realize it until after i woke up. 

Aluminum still does that deal in 1.01 and if you did do something with the ore recipe I am unsure why it's just aluminum that don't register properly.

**Comment by MiningMark48** [comment]
1.0.1 only added some configuration checking for registry issues, I'll take a look at aluminum and see if I messed up somewhere along the line with something.

**Comment by MiningMark48** [comment]
I believe I found the culprit, a simple misspelling of the word `aluminum`. 🤦‍♂️

**Comment by MiningMark48** [comment]
Bugs and features have been resolved, if you have any more suggestions feel free to tell me at http://miningmark48.xyz/teammcmdiscord
